name: fl_downloader
description: A plugin to download files using the native capabilities.
  URLSession on iOS, DownloadManager on Android and BITS on Windows.
version: 2.0.1+1
#homepage:
repository: https://github.com/inceptusp/fl_downloader

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.inceptusp.fl_downloader
        pluginClass: FlDownloaderPlugin
      ios:
        pluginClass: FlDownloaderPlugin
      windows:
        pluginClass: FlDownloaderPluginCApi
